# Generated by Django 4.2 on 2025-04-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SysUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=32, null=True, verbose_name="用户名"),
                ),
                (
                    "password",
                    models.CharField(max_length=32, null=True, verbose_name="密码"),
                ),
                (
                    "phone",
                    models.CharField(max_length=11, null=True, verbose_name="手机号"),
                ),
                (
                    "email",
                    models.CharField(max_length=32, null=True, verbose_name="邮箱"),
                ),
                (
                    "avatar",
                    models.CharField(max_length=256, null=True, verbose_name="头像"),
                ),
                (
                    "openid",
                    models.CharField(max_length=256, null=True, verbose_name="openid"),
                ),
                (
                    "unionid",
                    models.CharField(max_length=256, null=True, verbose_name="unionid"),
                ),
                (
                    "user_type",
                    models.SmallIntegerField(
                        choices=[(1, "普通用户"), (2, "管理员"), (3, "超级管理员")],
                        verbose_name="用户类型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
        ),
    ]
